# -*- coding: utf-8 -*-
"""servant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhWNj8X5rzcGBIa_c_dukUN1b4yISNTb
"""

from flask import Flask, request, jsonify
    import pickle # Or your model loading library

app =Flask(__name__)

import torch
import torch.nn as nn



from sklearn.linear_model import LinearRegression
import numpy as np

model = LinearRegression()
model.fit(np.array([[1],[2],[3]]), np.array([2,4,6])) # Dummy training
with open('linear_regression_model.pkl', 'wb') as f:
    pickle.dump(model, f)

@app.route('/predict', methods= ["POST"])
def predict():
  data = request.get_json()
  futui = np.array(data['features']).reshape(-1,1)
  predict = model.predict(futui)
  return jsonify({'prediction':predict[0].item()})

if __name__ == '__main__':
    app.run(debug=True)



